version: '3'

services:
    database:
        image: postgres:latest
        volumes:
            - oce_ics_psql:/var/lib/postgresql:rw
        ports:
            - "5432"
        environment:
            POSTGRES_USER: icsuser
            POSTGRES_PASSWORD: icspassword
            POSTGRES_DB: icsdb
        networks:
            - ics
 
    app:
        build:
            context: .
        volumes:
            - .:/app:rw
        networks:
            - ics
        depends_on:
            - database
        ports:
            - "8888:8888"
        environment:
            DB_USER: icsuser
            DB_PASSWORD: icspassword
            DB_HOST: database
            DB_NAME: icsdb
            DB_TYPE: postgres
            DB_SSL: 0

networks:
    ics:

volumes:
    oce_ics_psql:
